# Generated by Django 4.2.21 on 2025-06-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="記憶の内容")),
                ("song_title", models.CharField(max_length=200, verbose_name="曲名")),
                (
                    "artist_name",
                    models.CharField(max_length=200, verbose_name="アーティスト名"),
                ),
                ("spotify_url", models.URLField(verbose_name="SpotifyのURL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
                ),
            ],
            options={
                "verbose_name": "記憶",
                "verbose_name_plural": "記憶",
                "ordering": ["-created_at"],
            },
        ),
    ]
